### ISSUE TITLE
Footer link has incorrect VEC URL

### ISSUE THREAD

**Issue by MarinaNitze** [department-of-veterans-affairs/va_common#1]
Currently:
href="/employment/"

Should be:

href="/veterans-employment-center/"

**Comment by emilyville** [comment]
@MarinaMartin  so my bad on the terrible documentation of this - but the footer is autogenerated from the gem! I'm going to add this to my footer-issue list of fixes to make to the footer this evening. And again, I need to document this process. Maybe I will add a comment to the top mentioning it's an autogenerated file.

**Comment by emilyville** [comment]
yay - this is awesome.gem in action!
