### ISSUE TITLE
IE9 Compatibility Issue

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/va_common#11]
Please see screen shots from Browserstack for IE9 from VEC and GIBCT.

![bs_win7_ie_9 0 1](https://cloud.githubusercontent.com/assets/11138830/12276058/82bddaa8-b941-11e5-910e-956d1503acf6.jpg)
![bs_win7_ie_9 0](https://cloud.githubusercontent.com/assets/11138830/12276057/82bc7050-b941-11e5-8c61-91c90a6a5013.jpg)

**Comment by emilyville** [comment]
@dannychapman I tried a bunch of stuff to fix this - realized the html5shim wasn't loading as well the ie.css file, but it seems to have made no difference. Wondering if you'll take a look and see if I'm missing something obvious? The discrepancy between vets-website and everything else is pretty huge!

**Comment by emilyville** [comment]
with great happiness I am declaring the evil reign of IE9 over the va_common gem over with the update to 3.5.
