### ISSUE TITLE
Search Bar - Minor misalignment

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/va_common#20]
<img width="592" alt="screen shot 2016-02-03 at 8 25 57 pm" src="https://cloud.githubusercontent.com/assets/11138830/12802939/7b06f0c2-cab4-11e5-9ac0-8c201153b99f.png">

**Comment by emilyville** [comment]
Is this from gi, or across all repos (including vec)?

**Comment by rickleegit** [comment]
It appears to be CT specific. I am going to look into it today. Just added this so I would not forget.

**Comment by emilyville** [comment]
@rickleegit is this still an issue? From my quick 👀  it looks resolved.

**Comment by rickleegit** [comment]
Does appear to be resolved to me as well.
