### ISSUE TITLE
Does not work with Rails > 4.2.4

### ISSUE THREAD

**Issue by jeffmaher** [department-of-veterans-affairs/va_common#22]
Current runtime error on GI Bill Comparison Tool after changing the Rails version and running `bundle update`.

![image](https://cloud.githubusercontent.com/assets/950486/12832271/fd76a5fe-cb66-11e5-930b-b90164fba131.png)

Possible fix to investigate:
http://stackoverflow.com/questions/34471546/rails-not-precompiling-images-in-the-app-assets-images-folder

**Comment by ayaleloehr** [comment]
To get around this yesterday, I copied /app/assets/images/social-icons from va_common into this same folder location my own project.  Copying files around is probably not the long term solution though.

**Comment by jeffmaher** [comment]
Fixed
