### ISSUE TITLE
Why do we have generators?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/va_common#6]
It looks like these should just be static assets, no?

I would have expected that each version of va_common just have a header and footer that was "correct". That way when a project updated the gem, it would just get the new header/footer.

In the current mechanism, we are copying the header file which means everyone updating needs to do 2 steps: update the gem and then rerun the generator to overwrite the existing file.  That seems like more work and also means it's harder to version control the headers/footers out in the wild.

Also, it might be worth writing a va_common_yield or something that removes the header/footer boilerplate that you'd insert into the application.html.erb.

**Comment by awong-dev** [comment]
@emilyville @plusjeff

**Comment by emilyville** [comment]
Similar discussion as here:

https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/423

I couldn't find a way to include static html in the gem. Happy to have help
here if anyone wants to take a stab at this.

**Comment by awong-dev** [comment]
Take a look at #7

**Comment by emilyville** [comment]
closing 'cause done. Thanks @awong-dev !!
